#!/usr/bin/bash

source ./base

function Rectangle {
    local this="$1"
    Object "$this"

    p $this.a = "$2"
    p $this.b = "$3"
    p $this.square = "Rectangle.square"

    Rectangle.square() {
        local this="$1"
        local result=$(( $(p $this.a) * $(p $this.b) ))
        echo "$result"
    }
}